### ISSUE TITLE
Error occurs when keywords contain `@`

### ISSUE THREAD

**Issue by kawarimidoll** [tani/vim-typo#2]
I found `E474` is occurred using this plugin in a yaml file.
I ran `syntaxcomplete#OmniSyntaxList()` in yaml and found several keywords that begin with `@`. It appears that `iabbrev` cannot use `@` in lhs.
This may occur with other file types and other symbols.

**Comment by tani** [comment]
Thank you for reporting issue! The latest version will drop non-alphabetic keywords.
Please re-open issue if you still have any problem. Cheers!

**Comment by kawarimidoll** [comment]
Thanks, it's fixed. Nice work 🥰
